import = ["/Users/vitali/.config/alacritty/themes/solarized_light.toml"]
live_config_reload = true

[cursor.style]
shape = "Beam"

[font]
size = 20.0

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Semibold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Semibold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Regular Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "L"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Copy"
regex = '[tTdDpP]\d+'

[hints.enabled.binding]
key = "M"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
option_as_alt = "Both"
